{% metadata_file .yamato/project.metafile %}
---

{% for project in projects -%}
{% for editor in test_editors -%}
{% for platform in test_platforms -%}

build_{{ project.name }}_{{ editor }}_{{ platform.name }}:
  name: Build Project {{ projects.first.name }} - Package {{ package.name }} - {{ editor }} on {{ platform.name }}
  variables:
    UTR_VERSION: current
  agent:
      # Do not choose machines with gpus or connected devices to perform this step
      # If it takes a lot of time to compile your project prefer flavor with more cores.
      # See https://internaldocs.hq.unity3d.com/bokken/reference/flavors/
      type: Unity::VM
      image: sdet/gamecode_win10:latest
      flavor: b1.xlarge
  commands:
    - pip install unity-downloader-cli --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple --upgrade
    - unity-downloader-cli -u trunk -c editor --wait --published --fast
    - curl -s https://artifactory.prd.it.unity3d.com/artifactory/unity-tools-local/utr-standalone/utr  --output utr
    - chmod +x ./utr
    - ./utr --suite=playmode --platform=StandaloneLinux64
  artifacts:
    players:
        paths:
          - "build/players/**"
    logs:
        paths:
          - "build/logs/**"

# run_{{ project.name }}_{{ editor }}_{{ platform.name }}:
#   name: Run Test on a windows64 standalone player
#   variables:
#     UTR_VERSION: current
#   # no need to clone repo
#   skip_checkout: true
#   agent:
#       # Running tests is fast, building it not requried, therefore flavor can be smaller. see https://internaldocs.hq.unity3d.com/bokken/reference/flavors/
#       # Now we can use an 'expensive' type. 
#       type: Unity::VM
#       image: sdet/gamecode_win10:latest
#       flavor: b1.large
#   dependencies:
#     - .yamato/standalone_windows64.yml#build_{{ project.name }}_{{ editor }}_{{ platform.name }}
#   commands:
#     - curl -s https://artifactory.prd.it.unity3d.com/artifactory/unity-tools-local/utr-standalone/utr.bat --output utr.bat
#     - ./utr --suite=playmode --platform=StandaloneWindows64 --player-load-path=build/players --artifacts_path=build/test-results --player-connection-ip=auto
#   artifacts:
#     logs:
#         paths:
#           - "build/test-results/**"

{% endfor -%}
{% endfor -%}
{% endfor -%}

# Run all relevant tasks when a pull request targeting the develop
# branch is created or updated. Currently only mlapi package tests are
# enabled, since the others are missing test coverage and will fail CI.
# develop_pull_request_trigger:
#   name: Develop Branch Triggers
#   dependencies:
# {% for project in projects -%}
# {% for editor in test_editors -%}
# {% for platform in test_platforms -%}
#     - .yamato/build.yml#build_{{ project.name }}_{{ editor }}_{{ platform.name }}
# {% endfor -%}
# {% endfor -%}
# {% endfor -%}
#   triggers:
#     cancel_old_ci: true
#     pull_requests:
#     - targets:
#         only:
#           - "main"
#           - "develop"